### ISSUE TITLE
Colab

### ISSUE THREAD

**Issue by duerrsimon** [janjoswig/AlgoSB2021#1]
To use in colab install using this setup https://colab.research.google.com/drive/1zCpA_6-bmvhFGWwe0gfop3O7w2tmfb7j?usp=sharing

The environment.yml could also be made less specific using --from-history  when exporting.

**Comment by sokrypton** [comment]
Ditto:
https://colab.research.google.com/drive/12mLEfqFTFn1FENm4TUohiF3MSQgHbGKi

**Comment by sokrypton** [comment]
Here is the second exercise. Though I was not able to get nglview to work in colab. 
Anyone else able to?

https://colab.research.google.com/drive/1Tm_3rD6IE0IiNw1TrpqH3Jq7z7SuKoxs?usp=sharing

**Comment by duerrsimon** [comment]
nglviewer developers don't support it afaik.

**Comment by sokrypton** [comment]
py3Dmol works, and it could technically show MD trajectories. just need to figure out how to load them in correct format

**Comment by sokrypton** [comment]
Some instructions here :D 
https://colab.research.google.com/github/pb3lab/ibm3202/blob/master/tutorials/lab02_molviz.ipynb

**Comment by janjoswig** [comment]
Thanks a lot for your help! I added the `condacolab` instruction part to the README file.

`py3Dmol` looks interesting but for the scope of this exercise, it might be a bit too complicated to make it work for a trajectory.

It seems that Colab can work with `nglview` by adding this:

```python
from google.colab import output
output.enable_custom_widget_manager()
```
